### ISSUE TITLE
Cloze not working with multiple example with numbers inside

### ISSUE THREAD

**Issue by lucamolteni** [matthayes/anki_cloze_anything#1]
According to documentation

**Note:** You can have more than one field with cloze content per note.  For example, you could have fields `Example1Cloze` and `Example2Cloze`.  Each can be used to generate cards.

But this regexp 
```/^[^\d]+(\d+)$/```
Will match the first number and use it for the field.

By using

```
ExampleFirstCloze
ExampleFirstCloze1
ExampleFirstCloze2
```

and

```
ExampleSecondCloze
ExampleSecondCloze1
ExampleSecondCloze2
```

This works accordingly

**Comment by matthayes** [comment]
Ah thanks for pointing this out.  I intended for the regex to match the last number in the field name but currently it doesn't allow numbers within the field.  I'll update the documentation and improve the regex separately.

**Comment by matthayes** [comment]
Template fixed in https://github.com/matthayes/anki_cloze_anything/commit/1ffae38b0baf1c67c62acbe2d39092559b21ee98
