### ISSUE TITLE
Cloze replacement should support line feeds

### ISSUE THREAD

**Issue by kriswuollett** [matthayes/anki_cloze_anything#16]
Currently trying to quiz myself on some code examples in a `<pre>` block and use cloze on multiple chunks of code.

As a workaround I currently can put in multiple cloze entries with the same number, but that gives too big of a hint on how many lines are missing from the example.

**Comment by matthayes** [comment]
Thanks for reporting this and sorry for the late reply.  I have a fix which appears to work.  Please see the change: https://github.com/matthayes/anki_cloze_anything/commit/1952009b1b6dfb622bb39f8bcb348aeec3c8801d

If you'd like to simply copy the full script without having to make the edits in the commit above, you can see it here: https://github.com/matthayes/anki_cloze_anything/blob/support_line_feed/examples/cloze_anything.js

Please let me know if this fixes your issue or if you notice any problems.  I'll merge in the change sometime soon.

**Comment by matthayes** [comment]
Fixed in 1952009b1b6dfb622bb39f8bcb348aeec3c8801d

**Comment by matthayes** [comment]
Released in v0.3, which you can download [here](https://github.com/matthayes/anki_cloze_anything/releases/tag/v0.3).
