### ISSUE TITLE
New

### ISSUE THREAD

**Issue by jsreaves** [matthayes/anki_cloze_anything#21]
I'm on MacOS.

Under Anki 2.1.44, the plug-in button creates the cloze "((c1::blah))" but doesn't populate the FrontCloze1 field.

Under Anki 2.1.45, the plug-in button doesn't appear in the editor.

Fortunately, the keyboard shortcut still seems to work.

**Comment by matthayes** [comment]
Thanks for the report.  I see the same issue on 2.1.44.  Well that's annoying.  I'll look into it.  I know there have been some editor updates recently.

**Comment by rwmpelstilzchen** [comment]
In Anki 2.1.47 (dc156f34) <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>C</kbd> does not do anything and the icon does not appear either, so one has to type `((cN::` and `))` manually. `fooClozeN` are not populated automatically, but when Create Missing Cards is run they are and the appropriate cards are created.

**Comment by matthayes** [comment]
I fixed it!  I released a new version of the plugin.  Please update and try again.  I tested it on Anki 2.1.49.  Hopefully the upcoming 2.1.50 release won't break it.  Note that the new keyboard shortcut is Ctrl+Shift+W as I couldn't hook into Anki's cloze shortcut anymore.  Details of fix are here: https://github.com/matthayes/anki_cloze_anything/commit/8ea67d7f033242795ba42706b9006a8a6c70f669

**Comment by matthayes** [comment]
Note that I tested on the Anki beta for 2.1.50 and the plugin is only partially working.  I opened an issue to track it: https://github.com/matthayes/anki_cloze_anything/issues/23

**Comment by matthayes** [comment]
FYI there's a PR to fix the issue in 2.1.50, so this will probably be resolved before its release.
