### ISSUE TITLE
Only "expression" cards appear in review

### ISSUE THREAD

**Issue by Vitnim** [matthayes/anki_cloze_anything#32]
First time trying your system.  Behavior same on Ubuntu (Anki 2.1.56) and AnkiDroid (2.15.6).

After importing the sample deck, I see 12 new cards in the queue.  After I click 'study now,' the first card shows (Ik heb honger).  After reviewing, it goes to the first card from the next note (Ik heb dorst), and then to the first card from the next note (Hij heeft dorst).  After reviewing that third card (only three cards - not twelve), the new card queue number goes from 10 to zero and it tells me I have finished the deck.  On the 'decks' screen it shows all zeros from the deck.  I am unable to review any of the actual cloze deletion cards.

In the card browser all of the cloze deletion cards show 'new #X', and I am able to preview each card.  What on earth am I doing wrong?
Thanks

Coincidental anecdote: Dutch is actually the last deck I added to Anki.

**Comment by rwmpelstilzchen** [comment]
Are they just buried?
https://docs.ankiweb.net/studying.html#siblings-and-burying

**Comment by Vitnim** [comment]
Holy crap.  I have been using Anki since practically its inception and I have never, EVER even thought about the "bury" option.  Now I know and have gained extra humility in the process.  I guess clozed deletions is about to change my study routine even more dramatically than I expected.

Yes.  That was the issue.  Maybe this is common sense to others who have lots of sibling whatever cards, but it was new to me.  Maybe a quick note in the instructions to turn off burying - at least for new cards - in order for the sample deck to work as advertised?  Or maybe I will be the lone case of not getting it.

Thanks.

**Comment by rwmpelstilzchen** [comment]
I’m glad I was able to help :-)

>  I have been using Anki since practically its inception

Wow! That’s about 16 years ago! 😮
Respect…!
