### ISSUE TITLE
Update README: Specify AnkiDroid support

### ISSUE THREAD

**Issue by iliekprogrammar** [matthayes/anki_cloze_anything#9]
I only tested the [Cloze Anything sample/example](https://ankiweb.net/shared/info/1637056056) deck. So, if there's any more specific testing for AnkiDroid, let me know.

[Front](https://i.ibb.co/9wZzRpk/Screenshot-2020-06-05-17-13-05.jpg) and [back](https://i.ibb.co/fHKxhdM/Screenshot-2020-06-05-17-13-29.jpg) cards.

**Comment by matthayes** [comment]
Thanks for testing it!  That should be good.  I've updated the README and other documentation.
